[project]
name = "ml-rain-tomorrow-prediction"
version = "0.1.0"
description = "Machine Learning Project for Rain Tomorrow Prediction"
authors = [
    { name = "Nijat Akhundzada", email = "nicataxundzada@gmail.com" },
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = []
